"""The skills tree: the API reference the agent reads instead of guessing.

Each package gets a folder under ``spatial_intelligence/skills`` with an
authored ``index.md`` (what it is, how to reach it) and a generated ``api/``
holding one file per topic plus a catalog for the bulk subpackages. Generated
files carry a banner and appear in ``api/meta.json`` with their hash and the
package version they describe, so a stale tree is visible rather than silent.

Nothing here imports a package unless a tree is being built.
"""

from __future__ import annotations

import enum
import hashlib
import inspect
import json
from datetime import datetime, timezone
from pathlib import Path

from ..settings import env
from . import packages

#: Root of the committed trees (package data, shipped with the wheel).
SKILLS_DIR = Path(__file__).resolve().parent.parent / "skills"
#: Byte cap on one generated topic file; the overflow spills to ``<topic>-2.md``.
MAX_FILE_BYTES = 32_000
#: Symbols listed per topic before the file is truncated.
MAX_SYMBOLS = 120
#: Members listed for an enum before the rest are summarised.
MAX_ENUM_MEMBERS = 40
#: First-paragraph cap for a symbol's docstring.
MAX_SUMMARY = 400

#: Topics that are one class each: listed as a catalog table instead of a file
#: per class, because a package with 100 datasets must not cost 100 files.
CATALOG_TOPICS = frozenset({"datasets", "datamodules"})

BANNER = (
    "<!-- generated by spatial_intelligence.pythonruntime.spec; do not edit -->\n"
)


def tree_dir(package: str) -> Path:
    """Return the committed tree folder for ``package``."""
    return SKILLS_DIR / package


def cache_dir(package: str = "") -> Path:
    """Return the per-machine skills cache, where user files win."""
    root = env.skills_dir()
    return root / package if package else root


def packages_with_skills() -> list[str]:
    """Return the packages that have a tree in the repository."""
    if not SKILLS_DIR.is_dir():
        return []
    return sorted(
        entry.name
        for entry in SKILLS_DIR.iterdir()
        if (entry / "index.md").is_file() or (entry / "api").is_dir()
    )


def _summary(obj) -> str:
    """Return the first paragraph of a docstring, flattened and trimmed."""
    doc = inspect.getdoc(obj) or ""
    first = doc.split("\n\n", 1)[0]
    text = " ".join(first.split())
    return text[:MAX_SUMMARY]


def _signature(obj) -> str:
    try:
        return str(inspect.signature(obj))
    except (TypeError, ValueError):
        return ""


def _public(name: str) -> bool:
    return not name.startswith("_")


def _topics(package: str) -> list[tuple[str, object]]:
    """Return ``(topic, module)`` for each public submodule of ``package``.

    Walked with ``pkgutil`` rather than read off the package's attributes: a
    package's ``__init__`` is not obliged to import its own submodules, and the
    big ones (torchgeo, terratorch) mostly do not.
    """
    import importlib
    import pkgutil

    root = importlib.import_module(package)
    found: list[tuple[str, object]] = []
    for info in sorted(pkgutil.iter_modules(root.__path__), key=lambda item: item.name):
        if not _public(info.name):
            continue
        try:
            module = importlib.import_module(f"{package}.{info.name}")
        except Exception:  # noqa: BLE001 - one unimportable module is skipped, not fatal
            continue
        found.append((info.name, module))
    return found


def _with_submodules(module) -> list[tuple[str, object]]:
    """Return a topic module plus its public submodules, one level deep."""
    import importlib
    import pkgutil

    found = [(getattr(module, "__name__", ""), module)]
    for info in sorted(pkgutil.iter_modules(getattr(module, "__path__", [])), key=lambda i: i.name):
        if not _public(info.name):
            continue
        try:
            submodule = importlib.import_module(f"{module.__name__}.{info.name}")
        except Exception:  # noqa: BLE001 - optional submodules may need heavy deps
            continue
        found.append((getattr(submodule, "__name__", ""), submodule))
    return found


def _enum_members(value) -> list[str]:
    """Return an enum class's member names (weights enums are the common case)."""
    if not (inspect.isclass(value) and issubclass(value, enum.Enum)):
        return []
    return [member.name for member in value][:MAX_ENUM_MEMBERS]


def _symbol_lines(modules: list[tuple[str, object]]) -> list[str]:
    """Render the public classes and functions of a topic as reference lines."""
    lines: list[str] = []
    for module_path, module in modules:
        lines.extend(["", f"## {module_path}", ""])
        for name, value in sorted(vars(module).items()):
            if not _public(name):
                continue
            kind = "class" if inspect.isclass(value) else "function" if inspect.isroutine(value) else ""
            if not kind:
                continue
            signature = _signature(value)
            summary = _summary(value)
            lines.append(f"- `{name}{signature}` — {summary or kind}")
            members = _enum_members(value)
            if members:
                lines.append(f"  - members: {', '.join(members)}")
                if len(list(value)) > MAX_ENUM_MEMBERS:
                    lines.append(f"  - ... and {len(list(value)) - MAX_ENUM_MEMBERS} more")
            if len(lines) >= MAX_SYMBOLS:
                lines.append(f"- ... [truncated at {MAX_SYMBOLS} symbols]")
                return lines
    return lines


def _catalog_rows(modules: list[tuple[str, object]]) -> list[str]:
    """Render a table row per public class across a bulk topic's modules."""
    rows = ["| symbol | summary |", "|---|---|"]
    for module_path, module in modules:
        for name, value in sorted(vars(module).items()):
            if not _public(name) or not inspect.isclass(value):
                continue
            summary = _summary(value).replace("|", "\\|")
            rows.append(f"| `{module_path}.{name}` | {summary} |")
            if len(rows) >= MAX_SYMBOLS + 2:
                rows.append(f"| ... | [truncated at {MAX_SYMBOLS} classes] |")
                return rows
    return rows


def _write(path: Path, text: str) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def build(package: str, target: Path | None = None) -> dict:
    """Generate ``api/`` for an installed ``package`` and return its manifest.

    Writes topic files, a catalog per bulk topic, an ``api/index.md`` linking
    them, and ``api/meta.json`` recording the version and a hash per file. The
    default target is the committed tree, so a maintainer can regenerate and
    review the diff; a read-only install falls back to the writable cache.
    """
    package_meta = next((item for item in packages.PACKAGES if item.key == package), None)
    if package_meta is None or not packages.installed(package_meta):
        raise LookupError(f"{package} is not installed; nothing to describe")

    installed_version = packages.version(package_meta) or "unknown"
    root = target or tree_dir(package)
    try:
        (root / "api").mkdir(parents=True, exist_ok=True)
    except OSError:
        root = cache_dir(package)
        (root / "api").mkdir(parents=True, exist_ok=True)
    api = root / "api"
    files: dict[str, str] = {}
    index_lines = [
        BANNER,
        f"# {package} API — {installed_version}",
        "",
        "One file per topic; `skill(package, path=...)` reads one, "
        "`skill(package, query=...)` searches them all.",
        "",
    ]

    for topic, module in _topics(package):
        modules = _with_submodules(module)
        if topic in CATALOG_TOPICS:
            text = "\n".join(
                [BANNER, f"# {package}.{topic}", "", *_catalog_rows(modules), ""]
            )
            name = f"{topic}.catalog.md"
        else:
            text = "\n".join([BANNER, f"# {package}.{topic}", *_symbol_lines(modules)]) + "\n"
            name = f"{topic}.md"

        while len(text.encode("utf-8")) > MAX_FILE_BYTES:
            text = text[: MAX_FILE_BYTES // 2].rstrip() + "\n... [truncated]\n"
        files[name] = _write(api / name, text)
        index_lines.append(f"- [{topic}]({name})")

    index_lines.append("")
    files["index.md"] = _write(api / "index.md", "\n".join(index_lines))

    meta = {
        "package": package,
        "version": installed_version,
        "generator": "spatial_intelligence.pythonruntime.spec",
        "built_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "root": str(root),
        "files": files,
    }
    _write(api / "meta.json", json.dumps(meta, indent=2, sort_keys=True) + "\n")
    return meta


def main(argv: list[str] | None = None) -> int:
    """Regenerate the API trees named on the command line, or every known one.

    ``python -m spatial_intelligence.pythonruntime.spec torchgeo`` writes the
    committed tree when the package is installed and the directory is writable,
    and the per-machine cache otherwise.
    """
    import sys

    names = list(argv if argv is not None else sys.argv[1:])
    if not names:
        names = [package.key for package in packages.PACKAGES]
    built, skipped = [], []
    for name in names:
        try:
            meta = build(name)
        except LookupError as exc:
            skipped.append(f"{name}: {exc}")
            continue
        built.append(f"{name} {meta['version']} -> {meta['root']}")
    for line in built:
        print(line)
    for line in skipped:
        print(f"skipped {line}")
    return 0 if built else 1


if __name__ == "__main__":  # pragma: no cover - manual maintenance entry point
    raise SystemExit(main())


__all__ = [
    "BANNER",
    "CATALOG_TOPICS",
    "MAX_FILE_BYTES",
    "SKILLS_DIR",
    "build",
    "cache_dir",
    "main",
    "packages_with_skills",
    "tree_dir",
]
